sudo: required
services:
  - docker

before_install:
  - docker build -t sabin2000/eHouseholds .

script: 
  - docker run -e CI=true sabin2000/eHouseholds npm test -- --coverage

after_success: 
  - docker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY